<a href="https://colab.research.google.com/github/HromovAndrey/Laba_II_mood_2/blob/main/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [2]:
y = np.arange(1, 13)
print(y)
print(y.size)
print(y.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
12
int64


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [4]:
y = np.arange(1, 13)
matrix = y.reshape((3, 4))
matrix = matrix.astype(np.float32)
transposed_matrix = matrix.T
print(transposed_matrix)
print(transposed_matrix.dtype)

[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]
float32


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [5]:

x = np.zeros((8, 8), dtype=int)

x[1::2, ::2] = 1
x[::2, 1::2] = 1

print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [9]:
i = np.random.randint(0, 10,(4,3))
sum_columns = np.sum(i, axis=0)
sum_rows = np.sum(i, axis=1)
sum_total = np.sum(i)
print(i)
print(sum_columns)
print(sum_rows)
print(sum_total)

[[1 7 4]
 [5 7 2]
 [8 4 2]
 [4 3 0]]
[18 21  8]
[12 14 14  7]
47


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [11]:
i = np.random.randint(0, 10,(4,3))
matrix_minus_max = i - np.max(i, axis=1, keepdims=True)
print(matrix_minus_max)

[[-9 -6  0]
 [-3  0 -7]
 [-5 -1  0]
 [-1  0 -1]]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [ ]:

weight_small = 5
weight_medium = 10
weight_large = 25
weight_extra_large = 40

count_small = 20
count_medium = 5
count_large = 10
count_extra_large = 4

total_weight = (weight_small * count_small +
                weight_medium * count_medium +
                weight_large * count_large +
                weight_extra_large * count_extra_large)

print( total_weight)


# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.

In [13]:


weights = {
    'small': 5,
    'medium': 10,
    'large': 25,
    'extra_large': 40
}

ships = [
    {'small': 20, 'medium': 5, 'large': 10, 'extra_large': 4},
    {'small': 15, 'medium': 7, 'large': 5, 'extra_large': 2},
    {'small': 10, 'medium': 10, 'large': 15, 'extra_large': 5}

]

def calculate_total_weight(ship):
    total_weight = 0
    for container_type, count in ship.items():
        total_weight += weights[container_type] * count
    return total_weight

for index, ship in enumerate(ships):
    total_weight = calculate_total_weight(ship)
    print(f'Загальна маса вантажу на кораблі {index + 1}: {total_weight} т')

Загальна маса вантажу на кораблі 1: 560 т
Загальна маса вантажу на кораблі 2: 350 т
Загальна маса вантажу на кораблі 3: 725 т
